# Generated by Django 6.0.4 on 2026-05-01 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LorePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Используется в URL и QR-коде. Например: alpha, beta, vault-7', unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='HTML разрешён')),
                ('visible_hint', models.TextField(blank=True, help_text='Подсказка видимая на странице (необязательно)')),
                ('hidden_clue', models.TextField(blank=True, help_text='Прячется в HTML-комментарий в исходнике страницы')),
                ('is_secret', models.BooleanField(default=False, help_text='Секретная страница — не упоминается нигде явно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Страница лора',
                'verbose_name_plural': 'Страницы лора',
            },
        ),
        migrations.CreateModel(
            name='PageScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_first_visit', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='arg.lorepage')),
            ],
            options={
                'verbose_name': 'Скан / посещение',
                'verbose_name_plural': 'Сканы / посещения',
                'ordering': ['-timestamp'],
            },
        ),
    ]
