# Generated by Django 6.0.4 on 2026-05-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('message', models.TextField(blank=True)),
                ('agent_id', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField()),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('triggered_special', models.BooleanField(default=False, help_text='Ввёл ключевую фразу')),
                ('triggered_unlock', models.CharField(blank=True, help_text='Какой акт разблокировал', max_length=100)),
            ],
            options={
                'verbose_name': 'Обращение через форму',
                'verbose_name_plural': 'Обращения через форму',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterField(
            model_name='lorepage',
            name='hidden_clue',
            field=models.TextField(blank=True, help_text='Прячется в HTML-комментарий'),
        ),
        migrations.AlterField(
            model_name='lorepage',
            name='is_secret',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lorepage',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='lorepage',
            name='visible_hint',
            field=models.TextField(blank=True),
        ),
    ]
